In [1]:
import os
import numpy as np
import dask.dataframe as dd
import pandas as pd
import concurrent.futures
import warnings
import timeit
import time
warnings.filterwarnings("ignore")
import re
import matching

In [2]:
price_all_base = pd.read_csv('pp-complete.csv',header=None)

In [218]:
price_all_base[price_all_base[3] == 'LS21 1FU'].sort_values(2).drop_duplicates(subset=[3,7,8,11,12], keep='last')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
pk,,,,,,,,,,,,,,,,
LS21 1FU_1,{5A9D8B56-0189-68EB-E053-6B04A8C0D293},304995,2017-06-02 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 37,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_2,{582D0637-D781-8F22-E053-6C04A8C01BAC},289995,2017-06-07 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 31,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_3,{5A9D8B56-00C8-68EB-E053-6B04A8C0D293},269995,2017-06-13 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 33,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_4,{5A9D8B56-0184-68EB-E053-6B04A8C0D293},228995,2017-06-23 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 35,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_5,{5A9D8B56-0188-68EB-E053-6B04A8C0D293},220000,2017-06-28 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 2,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_6,{5A9D8B56-0187-68EB-E053-6B04A8C0D293},294995,2017-06-28 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 25,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_7,{5CF9903C-CDB6-7F13-E053-6C04A8C074B1},204995,2017-06-30 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 3,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_9,{5F54B81E-0D09-2B45-E053-6B04A8C01FB0},259995,2017-08-11 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 14,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_8,{61D8894E-8EF4-3DE6-E053-6C04A8C01207},219995,2017-08-11 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 17,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_10,{64342BFF-3549-422C-E053-6C04A8C0FB8A},234995,2017-09-06 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 36,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_11,{64342BFF-35E8-422C-E053-6C04A8C0FB8A},214995,2017-09-18 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 9,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_12,{64342BFF-35E9-422C-E053-6C04A8C0FB8A},227500,2017-09-29 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 7,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_13,{64342BFF-3605-422C-E053-6C04A8C0FB8A},199995,2017-09-29 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 10,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_14,{64342BFF-3533-422C-E053-6C04A8C0FB8A},219995,2017-09-29 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 30,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_15,{64342BFF-3668-422C-E053-6C04A8C0FB8A},228995,2017-09-29 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 27,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_16,{64342BFF-362C-422C-E053-6C04A8C0FB8A},250000,2017-10-27 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 1,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_17,{64342BFF-362D-422C-E053-6C04A8C0FB8A},399995,2017-11-03 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 5,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_18,{64342BFF-3688-422C-E053-6C04A8C0FB8A},199995,2017-11-10 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 28,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_19,{64342BFF-368B-422C-E053-6C04A8C0FB8A},224995,2017-11-17 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 19,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_20,{64342BFF-3676-422C-E053-6C04A8C0FB8A},409995,2017-11-20 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 11,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_21,{64342BFF-36C6-422C-E053-6C04A8C0FB8A},234995,2017-11-29 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 8,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_22,{666758D7-8EA2-3363-E053-6B04A8C0D74E},180000,2017-12-01 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 26,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_23,{64342BFF-369F-422C-E053-6C04A8C0FB8A},399995,2017-12-01 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 12,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_24,{64342BFF-36AD-422C-E053-6C04A8C0FB8A},200000,2017-12-08 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 22,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_25,{68FEB20C-3E63-38DA-E053-6C04A8C051AE},179995,2017-12-15 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 20,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_26,{666758D7-8EAF-3363-E053-6B04A8C0D74E},375000,2017-12-21 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 6,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_27,{68FEB20C-3E1E-38DA-E053-6C04A8C051AE},219995,2017-12-22 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 24,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_29,{68FEB20C-3E68-38DA-E053-6C04A8C051AE},200000,2018-01-12 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 29,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_28,{6B32222C-E57A-01F1-E053-6C04A8C0D2C8},189995,2018-01-12 00:00,LS21 1FU,F,Y,L,GARNETT MILL,APARTMENT 4,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_30,{919FEC06-0C28-9A90-E053-6C04A8C0A300},259950,2019-04-05 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 23,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_31,{A96E4ACC-C814-9205-E053-6C04A8C0DA09},255000,2019-06-04 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 34,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_32,{965B6D92-3372-95E4-E053-6C04A8C07729},240000,2019-08-16 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 32,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_33,{9FF0D96A-9724-11ED-E053-6C04A8C06383},199338,2019-12-17 00:00,LS21 1FU,O,N,F,GARNETT MILL,UNIT 38,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,B,A
LS21 1FU_34,{AE4D86D4-9851-4619-E053-6C04A8C03CD0},255000,2020-06-12 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 16,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_35,{B82222ED-8CD6-6691-E053-6B04A8C02FB2},269950,2020-10-02 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 15,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_36,{C8A3A576-DBED-0425-E053-6C04A8C0947B},278000,2021-03-29 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 21,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A
LS21 1FU_37,{C8A3A576-DDED-0425-E053-6C04A8C0947B},212500,2021-06-01 00:00,LS21 1FU,F,N,L,GARNETT MILL,APARTMENT 18,MILL WAY,NaN,OTLEY,LEEDS,WEST YORKSHIRE,A,A

In [21]:
df = pd.read_excel('20210702_pb_data_postcode_1.xlsx')

In [17]:
price_all_base = price_all_base.sort_values(2).drop_duplicates(subset=[3,7,8,11,12], keep='last')

In [22]:
def to_str(x):
    try:
        a = str(int(x))
    except:
        a = x
    return a

df['BUILDING_NUMBER']=df['BUILDING_NUMBER'].apply(lambda x:to_str(x))
df['SUB_BUILDING_NAME']=df['SUB_BUILDING_NAME'].apply(lambda x:to_str(x))
df['BUILDING_NAME']=df['BUILDING_NAME'].apply(lambda x:to_str(x))

In [19]:
price_all_base = matching.change_df(price_all_base,3)

In [219]:
def find_one(df,price_all_base,x):
    filt_postcode = matching.find_by_postcode(price_all_base,df.iloc[x]['POSTCODE_LOCATOR'])
    
    for i in range(len(filt_postcode.index)):
        
        if pd.isnull(filt_postcode.iloc[i][7]):
            if pd.isnull(filt_postcode.iloc[i][8]):
                continue
            if str(filt_postcode.iloc[i][8]) == str(df.iloc[x]['SUB_BUILDING_NAME']):
                return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
            continue
        name_num = filt_postcode.iloc[i][7]
        name_num_lst = name_num.split(', ')
        if len(name_num_lst) == 1:
            cur = name_num_lst[0]
            if cur[0].isdigit():
                if cur == df.iloc[x]['BUILDING_NUMBER']:
                    return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
                continue
            else:
                if cur == df.iloc[x]['BUILDING_NAME']:
                    if pd.isnull(df.iloc[x]['SUB_BUILDING_NAME']):
                        return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
                    elif df.iloc[x]['SUB_BUILDING_NAME'] == filt_postcode.iloc[i][8]:
                        return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
        else:
            if name_num_lst[0] == df.iloc[x]['BUILDING_NAME']:
                return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
            if name_num_lst[0] == df.iloc[x]['BUILDING_NUMBER']:
                return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
            if name_num_lst[1] == df.iloc[x]['BUILDING_NAME']:
                return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
            if name_num_lst[1] == df.iloc[x]['BUILDING_NUMBER']:
                return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]]
    
    for i in range(len(filt_postcode.index)):
        name_num = filt_postcode.iloc[i][7]
        name_num_lst = str(name_num).split()
        #print(name_num_lst)
        name_num_lst.append(filt_postcode.iloc[i][8])
        s1 = set(name_num_lst)
        a = str(df.iloc[x]['BUILDING_NUMBER']).split()
        b = str(df.iloc[x]['BUILDING_NAME']).split()
        c = str(df.iloc[x]['SUB_BUILDING_NAME']).split()
        a.extend(b)
        a.extend(c)
        #print(a)
        s2 = set(list(a))
        if np.nan in s1:
            s1.remove(np.nan)
        if np.nan in s2:
            s2.remove(np.nan)
        if 'nan' in s1:
            s1.remove('nan')
        if 'nan' in s2:
            s2.remove('nan')
        #print(s1,s2)
        if s1 == s2 and len(s1)!=0:
            return [filt_postcode.iloc[i][1],filt_postcode.iloc[i][2]] 
    return ['Not Found','Not Found']

In [220]:
find_one(df,price_all_base,35)

[320000, '2012-09-28 00:00']

In [205]:
df['last_sold_price'] = '-'
df['last_sold_date'] = '-'

In [211]:
for x in range(len(df.index)):
    res = find_one(df,price_all_base,x)
    df.loc[x,'last_sold_price'] = res[0]
    df.loc[x,'last_sold_date'] = res[1]
    if x%1000 == 0:
        print(x)
    if x%100000 == 0:
        df.to_excel('result.xlsx')
    elif x%10000 == 0:
        df.to_csv('result.csv')

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000
373000
374000
375000
376000
377000
378000
379000
380000
381000
382000
383000
384000
385000
386000
387000
388000
389000
390000
391000
392000
393000
394000
395000
396000
397000
398000
399000
400000
401000
402000
403000
404000
405000
406000
407000
408000
409000
410000
411000
412000
413000
414000
415000
416000
417000
418000
419000
420000
421000
422000
423000
424000
425000
426000
427000
428000
429000
430000
431000
432000
433000
434000
435000
436000
437000
438000
439000
440000
441000
442000
443000
444000
445000
446000
447000
448000
449000
450000
451000
452000
453000
454000
455000
456000
457000
458000
459000
460000
461000
462000
463000
464000
465000
466000
467000
468000
469000
470000
471000
472000
473000
474000
475000
476000
477000
478000
479000
480000
481000
482000
483000
484000
485000
486000
487000
488000
489000
490000
491000
492000
493000
494000
495000
496000
497000
498000
499000
500000
501000
502000
503000
504000
505000
506000
507000
508000
509000
510000
511000
512000

In [214]:
df.to_excel('result.xlsx')

In [227]:
for x in range(len(df.index)):
    if x%10000 == 0:
        print(x)
        
    if pd.isnull(df.iloc[x]['SUB_BUILDING_NAME']):
        continue
    res = find_one(df,price_all_base,x)
    df.loc[x,'last_sold_price'] = res[0]
    df.loc[x,'last_sold_date'] = res[1]

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000

In [229]:
df.to_excel('result.xlsx')

In [202]:
################### Testing

In [ ]:
265668

In [215]:
df_sample = df.sample(n=1000)

In [217]:
df_sample[:50]

,SECTOR,SUB_BUILDING_NAME,BUILDING_NAME,BUILDING_NUMBER,STREET,TOWN,ADMINISTRATIVE_AREA,POSTCODE_LOCATOR,UPRN,UDPRN,TYPE,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,last_sold_price,last_sold_date
398701,WF4 2,NaN,NaN,8,INGS CLOSE,WAKEFIELD,WAKEFIELD,WF4 2HX,63058279,26424030.0,Semi-Detached,439484.68,414470.07,53.625300,-1.404475,Not Found,Not Found
55489,DN7 4,NaN,NaN,5,KEMPTON DRIVE,DONCASTER,DONCASTER,DN7 4QA,100050739263,7282906.0,Detached,464460.00,407901.00,53.563794,-1.028260,84950,2001-05-04 00:00
217839,LS21 1,APARTMENT 29,GARNETT MILL,NaN,MILL WAY,OTLEY,LEEDS,LS21 1FU,72747487,53978084.0,Flat/Maisonette,420416.38,446086.29,53.910547,-1.690700,304995,2017-06-02 00:00
481775,YO23 7,NaN,THE PADDOCKS,NaN,DAW LANE,SELBY,NORTH YORKSHIRE,YO23 7BL,200001019345,27357768.0,Detached,456011.00,442177.00,53.872802,-1.149618,Not Found,Not Found
461189,WF8 4,NaN,23 QUEENS HOTEL APARTMENTS,NaN,FRONT STREET,PONTEFRACT,WAKEFIELD,WF8 4DB,63168311,50397297.0,Flat/Maisonette,445049.87,422026.10,53.692764,-1.319244,101538,2013-11-05 00:00
313472,WF10 3,NaN,NaN,7,KERSHAW AVENUE,CASTLEFORD,WAKEFIELD,WF10 3EX,63060481,26504913.0,Terraced,444752.42,425108.80,53.720494,-1.323305,Not Found,Not Found
41480,DN6 0,NaN,NaN,6,SUTTON ROAD,DONCASTER,DONCASTER,DN6 0AH,100050780806,7266217.0,Semi-Detached,455964.00,412882.00,53.609532,-1.155622,Not Found,Not Found
441022,WF7 7,NaN,NaN,2,THE QUARRY,PONTEFRACT,WAKEFIELD,WF7 7GF,63198635,55512156.0,Detached,443249.30,416133.97,53.639959,-1.347328,500000,2020-12-21 00:00
71768,DN8 5,NaN,NaN,153,WIKE GATE ROAD,DONCASTER,DONCASTER,DN8 5JH,100051985581,7294624.0,Terraced,469548.00,413384.00,53.612420,-0.950235,Not Found,Not Found
260874,LS28 6,NaN,NaN,9,STANNINGLEY ROAD,LEEDS,LEEDS,LS28 6NT,72198945,14149392.0,Flat/Maisonette,422831.00,434756.00,53.808614,-1.654783,Not Found,Not Found
333727,WF11 9,1,THE PALACE,NaN,AIRE STREET,KNOTTINGLEY,WAKEFIELD,WF11 9AZ,63155686,26524160.0,Semi-Detached,450418.16,424163.62,53.711485,-1.237608,102500,2006-03-01 00:00
27482,DN14 6,NaN,NaN,21,WELLS GROVE,GOOLE,EAST RIDING OF YORKSHIRE,DN14 6RN,100050069287,7344396.0,Semi-Detached,473755.00,424870.00,53.715064,-0.883932,Not Found,Not Found
431476,WF6 2,NaN,NaN,1,ST MARY'S AVENUE,NORMANTON,WAKEFIELD,WF6 2PU,63105383,26455241.0,Semi-Detached,437886.17,423767.50,53.708981,-1.427513,Not Found,Not Found
337250,WF17 0,NaN,NaN,21,CORONATION TERRACE,BATLEY,KIRKLEES,WF17 0DP,83142113,26572041.0,Terraced,422793.00,426426.00,53.733747,-1.655971,Not Found,Not Found
54132,DN6 9,NaN,NaN,7,ARUNDEL ROAD,DONCASTER,DONCASTER,DN6 9ET,100050693085,7278017.0,Terraced,454728.01,415462.00,53.632848,-1.173849,81250,2002-10-11 00:00
333723,WF11 9,NaN,NaN,13,EAST ACRES,SELBY,NORTH YORKSHIRE,WF11 9DX,100050505930,26524739.0,Semi-Detached,449046.00,425537.00,53.723958,-1.258179,126500,2007-05-11 00:00
431130,WF6 2,NaN,NaN,19,PARKER AVENUE,NORMANTON,WAKEFIELD,WF6 2NS,63086054,26454848.0,Semi-Detached,437493.80,423631.10,53.707783,-1.433473,120000,2018-05-31 00:00
259137,LS28 5,NaN,28 MARSDEN COURT,NaN,WATER LANE,PUDSEY,LEEDS,LS28 5SH,72276541,14146906.0,Flat/Maisonette,421690.00,435238.00,53.812995,-1.672076,Not Found,Not Found
46814,DN6 7,NaN,NaN,57,STRETTON STREET,DONCASTER,DONCASTER,DN6 7UH,10006713760,54321685.0,Terraced,452741.91,408907.44,53.574144,-1.204987,162995,2017-12-22 00:00
419636,WF5 8,NaN,NaN,73,KINGSWAY CLOSE,OSSETT,WAKEFIELD,WF5 8DZ,63062015,26442115.0,Terraced,427285.62,421425.97,53.688593,-1.588309,Not Found,Not Found
149874,LS11 0,NaN,NaN,16,COTTINGLEY COURT,LEEDS,LEEDS,LS11 0HP,72682101,51754895.0,Flat/Maisonette,427653.00,430222.00,53.767631,-1.581964,Not Found,Not Found
54441,DN7 4,NaN,31 ABBEY WALK MOBILE HOME PARK,NaN,BOOTHAM LANE,DONCASTER,DONCASTER,DN7 4JT,200002732738,7282207.0,Caravan,465613.00,410139.00,53.583764,-1.010385,Not Found,Not Found
411881,WF4 6,NaN,NaN,4,WINDYRIDGE STREET,WAKEFIELD,WAKEFIELD,WF4 6ES,63127409,26436245.0,Semi-Detached,428721.72,418586.00,53.662992,-1.566826,190000,2016-09-29 00:00
421152,WF5 9,NaN,NaN,69,WOOD STREET,OSSETT,WAKEFIELD,WF5 9NU,63128001,26445856.0,Semi-Detached,427636.30,421780.95,53.691766,-1.582968,Not Found,Not Found
247503,LS27 8,NaN,NaN,6,MERLIN CLOSE,MORLEY,LEEDS,LS27 8TS,72413905,14138031.0,Terraced,427131.00,427310.00,53.741486,-1.590137,33000,1997-01-24 00:00
142835,LS10 4,NaN,NaN,17,GRANGE FIELDS ROAD,LEEDS,LEEDS,LS10 4QJ,72262777,13927214.0,Semi-Detached,431987.00,428896.00,53.755467,-1.516353,Not Found,Not Found
198666,LS13 4,NaN,NaN,27,WELLSTONE AVENUE,LEEDS,LEEDS,LS13 4DY,72225818,13977460.0,Terraced,423809.00,434080.00,53.802495,-1.639984,Not Found,Not Found
290358,WF1 3,NaN,NaN,24,MOXON STREET,WAKEFIELD,WAKEFIELD,WF1 3HB,63078523,26372446.0,Terraced,433117.66,423914.00,53.710620,-1.499736,132500,2019-09-13 00:00
44513,DN6 7,NaN,NaN,10,SWINBURNE AVENUE,DONCASTER,DONCASTER,DN6 7DJ,100050781118,7269518.0,Semi-Detached,453304.00,408372.00,53.569276,-1.196590,Not Found,Not Found
292026,WF1 3,NaN,NaN,28,BLENHEIM ROAD,WAKEFIELD,WAKEFIELD,WF1 3JZ,63011204,NaN,Flat/Maisonette,433007.44,421756.42,53.691235,-1.501634,Not Found,Not Found
36813,DN14 8,NaN,NaN,30,RIVERSIDE,RAWCLIFFE,EAST RIDING OF YORKSHIRE,DN14 8RN,10091610740,53685154.0,Semi-Detached,468289.23,423147.93,53.700331,-0.967114,Not Found,Not Found
252971,LS27 9,NaN,NaN,41,HORSFALL STREET,MORLEY,LEEDS,LS27 9QY,72358400,14141852.0,Flat/Maisonette,425648.00,428705.00,53.754099,-1.612506,Not Found,Not Found
228771,LS22 6,NaN,NaN,26,PENTAGON WAY,WETHERBY,LEEDS,LS22 6AW,72759176,54540805.0,Terraced,439468.15,449052.38,53.936109,-1.400316,Not Found,Not Found
207622,LS19 7,NaN,NaN,13,ST ANDREWS COURT,LEEDS,LEEDS,LS19 7UQ,72298847,14064977.0,Terraced,420956.00,441534.00,53.869611,-1.682796,Not Found,Not Found
97364,HG2 0,NaN,NaN,46,COLLEGE ROAD,HARROGATE,NORTH YORKSHIRE,HG2 0AQ,100050387796,10716517.0,Semi-Detached,429139.00,453934.00,53.980663,-1.557178,305000,2020-10-09 00:00
86193,HG1 3,NaN,NaN,24,SOUTHVILLE TERRACE,HARROGATE,NORTH YORKSHIRE,HG1 3HH,100050408181,10706120.0,Terraced,429420.00,456949.00,54.007744,-1.552604,250000,2003-06-20 00:00
334477,WF11 9,NaN,NaN,88,AIRE WALK,KNOTTINGLEY,WAKEFIELD,WF11 9NL,63001295,26525881.0,Flat/Maisonette,450347.50,424121.00,53.711109,-1.238686,Not Found,Not Found
87139,HG1 4,NaN,NaN,24,KINGSLEY CLOSE,HARROGATE,NORTH YORKSHIRE,HG1 4RA,100050397791,10711952.0,Semi-Detached,432652.00,455920.00,53.998303,-1.503401,210000,2012-05-04 00:00
16170,DN12 2,NaN,NaN,135,DAYLANDS AVENUE,DONCASTER,DONCASTER,DN12 2NS,100050716861,7329281.0,Semi-Detached,450261.00,398333.00,53.479349,-1.244141,Not Found,Not Found
155940,LS11 7,NaN,NaN,39,CROSS FLATTS TERRACE,LEEDS,LEEDS,LS11 7JW,72053555,13939695.0,Terraced,428853.00,430832.00,53.773049,-1.563703,Not Found,Not Found
37036,DN14 8,NaN,NaN,34,HIGH STREET,RAWCLIFFE,EAST RIDING OF YORKSHIRE,DN14 8QW,100050061715,7350754.0,Terraced,468582.00,423073.00,53.699619,-0.962697,125000,2018-04-27 00:00
275092,LS9 6,NaN,NaN,5,SEAFORTH PLACE,LEEDS,LEEDS,LS9 6AF,72181360,13899865.0,Terraced,432376.00,435097.00,53.811175,-1.509804,75000,2018-10-04 00:00
349657,WF17 8,APARTMENT 51,THE JUBILEE MILL,NaN,UPPER BLAKERIDGE LANE,BATLEY,KIRKLEES,WF17 8FR,83246208,53893921.0,Flat/Maisonette,423946.71,424365.45,53.715175,-1.638642,7434512,2017-04-28 00:00
256628,LS28 5,NaN,NaN,34,CHERRY TREE CRESCENT,PUDSEY,LEEDS,LS28 5SR,72274139,14147038.0,Semi-Detached,422003.00,435391.00,53.814357,-1.667311,196500,2005-07-01 00:00
306197,WF10 2,NaN,NaN,55,KESWICK DRIVE,CASTLEFORD,WAKEFIELD,WF10 2RD,63060693,26503054.0,Semi-Detached,446223.02,426644.52,53.734168,-1.300793,Not Found,Not Found
336285,WF17 0,NaN,NaN,7,LARCH CLOSE,BATLEY,KIRKLEES,WF17 0EA,83156560,26572190.0,Semi-Detached,423062.00,426651.00,53.735758,-1.651877,Not Found,Not Found
331312,WF11 8,NaN,NaN,3,BRONTE AVENUE,KNOTTINGLEY,WAKEFIELD,WF11 8QH,63014274,26523111.0,Terraced,447787.86,423762.92,53.708130,-1.277517,Not Found,Not Found
325861,WF10 5,NaN,19A,19,BEANCROFT ROAD,CASTLEFORD,WAKEFIELD,WF10 5BN,63175954,28253002.0,Flat/Maisonette,442629.12,425379.52,53.723105,-1.355442,56000,2003-10-23 00:00
425997,WF6 1,NaN,11A,11,ALEXANDRA DRIVE,NORMANTON,WAKEFIELD,WF6 1JT,63175913,26449506.0,Semi-Detached,438653.00,421500.00,53.688545,-1.416178,94000,2006-03-03 00:00
467198,WF9 2,NaN,NaN,25,FOXHUNTERS WAY,PONTEFRACT,WAKEFIELD,WF9 2SB,63153947,26486991.0,Semi-Detached,446782.75,410371.47,53.587865,-1.294753,43950,2002-01-31 00:00

In [221]:
find_one(df,price_all_base,217839)

[200000, '2018-01-12 00:00']

In [193]:
df_sample = df_sample.reset_index()

In [195]:
df_sample['last_sold_price'] = '-'
df_sample['last_sold_date'] = '-'

In [196]:
for x in range(len(df_sample.index)):
    res = find_one(df_sample,price_all_base,x)
    df_sample.loc[x,'last_sold_price'] = res[0]
    df_sample.loc[x,'last_sold_date'] = res[1]
    if x%100 == 0:
        print(x)

0
100
200
300
400
500
600
700
800
900

In [200]:
df_sample[df_sample['last_sold_price'] != 'Not Found']

,index,SECTOR,SUB_BUILDING_NAME,BUILDING_NAME,BUILDING_NUMBER,STREET,TOWN,ADMINISTRATIVE_AREA,POSTCODE_LOCATOR,UPRN,UDPRN,TYPE,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,last_sold_price,last_sold_date
2,40172,DN14 9,NaN,NaN,15,CHURCH FIELDS,SELBY,NORTH YORKSHIRE,DN14 9QH,10001153194,7353246.0,Terraced,464503.00,423865.00,53.707255,-1.024305,155000,2019-06-27 00:00
6,415722,WF5 0,NaN,NaN,23,CHARLES STREET,OSSETT,WAKEFIELD,WF5 0LR,63020385,26439141.0,Semi-Detached,429009.13,419416.65,53.670442,-1.562399,138000,2012-03-23 00:00
7,317736,WF10 4,NaN,NaN,13,MORRISON STREET,CASTLEFORD,WAKEFIELD,WF10 4BE,63077739,26509494.0,Terraced,443398.19,425337.34,53.722662,-1.343794,135000,2020-01-24 00:00
8,186217,LS13 1,NaN,NaN,53,NARROWBOAT WHARF,LEEDS,LEEDS,LS13 1RE,72515257,13968008.0,Flat/Maisonette,422657.00,436321.00,53.822688,-1.657311,192500,2021-02-12 00:00
17,226491,LS22 6,NaN,NaN,42,ULLSWATER DRIVE,WETHERBY,LEEDS,LS22 6YF,72395357,14084958.0,Detached,439490.00,448629.00,53.932302,-1.400038,305000,2004-10-18 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,253226,LS27 9,NaN,NaN,4,BUSELY COURT,MORLEY,LEEDS,LS27 9SJ,72415297,14142329.0,Flat/Maisonette,425950.00,428356.00,53.750947,-1.607955,89950,2014-03-21 00:00
992,35572,DN14 8,NaN,NaN,78,KINGS CAUSEWAY,SWINEFLEET,EAST RIDING OF YORKSHIRE,DN14 8DL,10033216777,28291482.0,Detached,477582.00,421860.00,53.687462,-0.826712,220000,2017-08-04 00:00
994,323946,WF10 5,NaN,NaN,62,AKETON ROAD,CASTLEFORD,WAKEFIELD,WF10 5DL,63001422,26515144.0,Terraced,442072.82,425056.77,53.720249,-1.363916,95000,2019-08-30 00:00
996,215852,LS21 1,NaN,NaN,21,CAMBRIDGE GROVE,OTLEY,LEEDS,LS21 1DH,72344268,14071898.0,Semi-Detached,420794.00,445212.00,53.902674,-1.685011,170000,2013-12-16 00:00
998,490620,YO41 1,NaN,THE CHICORY BARN,NaN,MOOR LANE,STAMFORD BRIDGE,EAST RIDING OF YORKSHIRE,YO41 1HU,10002820936,27436222.0,Detached,472885.00,454634.00,53.982650,-0.890065,50000,1999-10-29 00:00

In [151]:
find_one(df,price_all_base,188271)

[238000, '2018-09-17 00:00']

In [161]:
df_old = pd.read_excel('merged_pb.xlsx')